version: 0.0
os: linux
files:
  - source: /
    destination: /node
permissions:
  - object: /root
    owner: root
    group: root
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: post_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: validate.sh
      timeout: 60
      runas: root